import { Header } from '@/components/Header/header';
import { Providers } from '@/lib/Providers';
import { theme } from '@/styles/theme';
import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={poppins.className}>
                <ChakraProvider theme={theme}>
                    <Header />
                    {children}
                </ChakraProvider>
            </body>
        </html>
    );
}
